image: "python:3.7"

before_script:
  - python --version
  - pip install -r src/requirements.txt

stages:
  - Static Analysis
  - Build
  - Test
  - Deploy

mypy:
  stage: Static Analysis
  script:
  - pwd
  - ls -l

flake8:
  stage: Static Analysis
  script:
  - flake8 --max-line-length=120 bild/*.py

pylint:
  stage: Static Analysis
  allow_failure: true
  script:
  - pylint -d C0301 src/core/*.py
  - pylint -d C0301 src/api/*.py

install:
  image: cypress/base:10
  stage: Build

  script:
    - npm ci
    - npx cypress cache path
    - npx cypress cache list
    - $(npm bin)/print-env CI
    - npm run cy:verify
    - npm run cy:info

unit_test:
  stage: Test
  script:
  - cd src
  - python manage.py test

e2e_test:
  stage: Test
  script:
    - python src/manage.py runserver & node_modules/.bin/cypress run

deploy_staging:
  stage: Deploy

  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=timetravelmaps --api-key=8e8a1068-2e7b-4937-9f65-e684fe93d6e7
  only:
  - master
  - dev
  - heroku
