# Generated by Django 3.0.6 on 2020-05-17 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x_coord', models.IntegerField()),
                ('y_coord', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x_coord', models.IntegerField()),
                ('y_coord', models.IntegerField()),
                ('type', models.CharField(max_length=30)),
                ('prediction', models.IntegerField()),
                ('tiles_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tiles')),
            ],
        ),
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('water_prediction', models.IntegerField()),
                ('land_prediction', models.IntegerField()),
                ('buildings_prediction', models.IntegerField()),
                ('tiles_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tiles')),
            ],
        ),
    ]
