# Generated by Django 3.0.6 on 2020-05-20 17:16

from django.db import migrations


# pylint: disable=all
# generated by django
class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_captchasubmissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='captchasubmissions',
            old_name='buildings',
            new_name='building',
        ),
    ]
