# Generated by Django 3.0.6 on 2020-05-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedCaptchas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x_coord', models.IntegerField()),
                ('y_coord', models.IntegerField()),
                ('year', models.IntegerField()),
                ('water_prediction', models.IntegerField()),
                ('land_prediction', models.IntegerField()),
                ('buildings_prediction', models.IntegerField()),
                ('church_prediction', models.IntegerField()),
                ('oiltank_prediction', models.IntegerField()),
            ],
        ),
    ]
