# Generated by Django 3.0.6 on 2020-06-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_confirmedcaptchas'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsableTiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x_coord', models.IntegerField()),
                ('y_coord', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
