# Generated by Django 3.0.6 on 2020-06-10 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usabletiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x_coord', models.IntegerField()),
                ('y_coord', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CaptchaTiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x_coord', models.IntegerField()),
                ('y_coord', models.IntegerField()),
                ('year', models.IntegerField()),
                ('uuid', models.CharField(blank=True, max_length=32)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='objects',
            name='x_coord',
        ),
        migrations.RemoveField(
            model_name='objects',
            name='y_coord',
        ),
        migrations.CreateModel(
            name='CaptchaObjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
                ('prediction', models.IntegerField()),
                ('tiles_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CaptchaTiles')),
            ],
        ),
        migrations.CreateModel(
            name='CaptchaCharacteristics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('water_prediction', models.IntegerField()),
                ('land_prediction', models.IntegerField()),
                ('buildings_prediction', models.IntegerField()),
                ('tiles_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CaptchaTiles')),
            ],
        ),
        migrations.CreateModel(
            name='AIObjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
                ('prediction', models.IntegerField()),
                ('tiles_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AITiles')),
            ],
        ),
        migrations.CreateModel(
            name='AICharacteristics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('water_prediction', models.IntegerField()),
                ('land_prediction', models.IntegerField()),
                ('buildings_prediction', models.IntegerField()),
                ('tiles_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AITiles')),
            ],
        ),
    ]
