# Generated by Django 3.0.6 on 2020-06-10 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200610_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmed_Captcha_Tiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x_coord', models.IntegerField()),
                ('y_coord', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='AICharacteristics',
            new_name='AI_Characteristics',
        ),
        migrations.RenameModel(
            old_name='AIObjects',
            new_name='AI_Objects',
        ),
        migrations.RenameModel(
            old_name='AITiles',
            new_name='AI_Tiles',
        ),
        migrations.RenameModel(
            old_name='CaptchaCharacteristics',
            new_name='Captcha_Characteristics',
        ),
        migrations.RenameModel(
            old_name='CaptchaObjects',
            new_name='Captcha_Objects',
        ),
        migrations.RenameModel(
            old_name='CaptchaTiles',
            new_name='Captcha_Tiles',
        ),
        migrations.CreateModel(
            name='Confirmed_Captcha_Characteristics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('water_prediction', models.IntegerField()),
                ('land_prediction', models.IntegerField()),
                ('buildings_prediction', models.IntegerField()),
                ('tiles_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Confirmed_Captcha_Tiles')),
            ],
        ),
        migrations.CreateModel(
            name='Confimed_Captcha_Objects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
                ('prediction', models.IntegerField()),
                ('tiles_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Confirmed_Captcha_Tiles')),
            ],
        ),
    ]
