# Generated by Django 3.0.6 on 2020-06-12 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200610_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ai_characteristics',
            name='id',
        ),
        migrations.RemoveField(
            model_name='captcha_characteristics',
            name='id',
        ),
        migrations.RemoveField(
            model_name='characteristics',
            name='id',
        ),
        migrations.RemoveField(
            model_name='confirmed_captcha_characteristics',
            name='id',
        ),
        migrations.AlterField(
            model_name='ai_characteristics',
            name='tiles_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.AI_Tiles'),
        ),
        migrations.AlterField(
            model_name='captcha_characteristics',
            name='tiles_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.Captcha_Tiles'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='tiles_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.Tiles'),
        ),
        migrations.AlterField(
            model_name='confirmed_captcha_characteristics',
            name='tiles_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.Confirmed_Captcha_Tiles'),
        ),
    ]
