# Generated by Django 3.0.6 on 2020-06-19 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_ai_characteristics_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaptchaSubmissions',
        ),
        migrations.DeleteModel(
            name='ConfirmedCaptchas',
        ),
    ]
