"""Manager module"""
# !/usr/bin/env python
import os
import sys
# pylint: disable=all
# generated by django
if __name__ == '__main__':
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'api.settings')
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc

    ### UNCOMMENT FOR COVERAGE REPORT ###
    from django.core.management import execute_from_command_line

    is_testing = 'test' in sys.argv

    if is_testing:
        import coverage

        cov = coverage.coverage(source=['core', 'scripts'],
                                omit=['*core/test/*', '*/migrations/*', '*core/apps.py*', '*core/__init__.py*'],
                                branch=True)
        cov.erase()
        cov.start()

    execute_from_command_line(sys.argv)

    if is_testing:
        cov.stop()
        cov.save()
        cov.html_report()
